(() => {
  const telegram = window.Telegram && window.Telegram.WebApp;
  const root = document.getElementById('app');
  const initData = telegram ? telegram.initData : '';
  if (telegram) { telegram.ready(); telegram.expand(); }
  const state = { library: [], selected: null, episode: null, translation: null, quality: null, player: null };
  const esc = value => String(value ?? '').replace(/[&<>"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
  async function api(path, options = {}) {
    const headers = { ...(options.headers || {}) };
    if (initData) headers['X-Telegram-Init-Data'] = initData;
    if (options.body) headers['Content-Type'] = 'application/json';
    const response = await fetch(path, { ...options, headers, credentials: 'same-origin' });
    if (!response.ok) { const body = await response.json().catch(() => ({})); throw new Error(body.detail || 'Не удалось выполнить запрос.'); }
    return response.status === 204 ? null : response.json();
  }
  const fail = error => { root.innerHTML = `<p class="error">${esc(error.message || error)}</p>`; };
  function back() { telegram?.BackButton.hide(); home(); }
  function useBack() { telegram?.BackButton.show(); telegram?.BackButton.onClick(back); }
  async function home() {
    try {
      telegram?.BackButton.hide();
      const data = await api('/api/library'); state.library = data.items;
      root.innerHTML = `<h1>Anime365</h1><button class="action" id="search">Найти аниме</button><h2>Продолжить просмотр</h2>${cards(data.continue, true)}<h2>Смотрю</h2>${cards(data.items)}`;
      document.getElementById('search').onclick = search;
      root.querySelectorAll('[data-series]').forEach(button => button.onclick = () => details(Number(button.dataset.series)));
    } catch (error) { fail(error); }
  }
  function cards(items, resume = false) {
    if (!items.length) return '<p class="empty">Пока здесь пусто.</p>';
    return `<section class="grid">${items.map(item => `<article class="card"><button data-series="${item.series_id}"><strong>${esc(item.title)}</strong><div class="meta">${esc(item.last_watched_episode_number || 0)} / ${esc(item.last_available_episode_number || '?')}${resume && item.playback ? ` · ${Math.floor(item.playback.position_seconds / 60)}:${String(Math.floor(item.playback.position_seconds % 60)).padStart(2,'0')}` : ''}</div></button></article>`).join('')}</section>`;
  }
  async function search() {
    root.innerHTML = '<h1>Каталог</h1><input id="query" placeholder="Название аниме"><button class="action" id="go">Найти</button><section id="results"></section><button class="action secondary back">Назад</button>';
    useBack(); root.querySelector('.back').onclick = back;
    root.querySelector('#go').onclick = async () => { try { const data = await api(`/api/catalog?query=${encodeURIComponent(root.querySelector('#query').value)}`); root.querySelector('#results').innerHTML = cards(data.items); root.querySelectorAll('[data-series]').forEach(button => button.onclick = async () => { const item = data.items.find(row => Number(row.id) === Number(button.dataset.series)); await api('/api/library', { method:'POST', body: JSON.stringify({ series_id:item.id, title:item.titles?.ru || item.titles?.romaji || item.titles?.en || 'Без названия', year:item.year, series_type:item.typeTitle || item.type }) }); details(item.id); }); } catch(error) { fail(error); } };
  }
  async function details(seriesId) {
    try { const data = await api(`/api/library/${seriesId}`); state.selected = data; const p = data.playback; root.innerHTML = `<h1>${esc(data.item.title)}</h1><p class="meta">Просмотрено: ${esc(data.item.last_watched_episode_number || 0)} / ${data.episodes.length}</p>${p ? `<button class="action" id="resume">Продолжить с ${Math.floor(p.position_seconds/60)}:${String(Math.floor(p.position_seconds%60)).padStart(2,'0')}</button>` : ''}<h2>Серии</h2><div class="episodes">${data.episodes.map(ep => `<button class="action ${ep.watched ? 'secondary' : ''}" data-episode="${ep.id}">${ep.watched ? '✓ ' : ''}${esc(ep.number)}</button>`).join('')}</div><button class="action secondary back">Назад</button>`; useBack(); root.querySelector('.back').onclick = back; if (p) root.querySelector('#resume').onclick = () => selectEpisode(p.episode_id); root.querySelectorAll('[data-episode]').forEach(button => button.onclick = () => selectEpisode(Number(button.dataset.episode))); } catch(error) { fail(error); }
  }
  async function selectEpisode(episodeId) { try { state.episode = state.selected.episodes.find(item => item.id === episodeId); const data = await api(`/api/episodes/${episodeId}/translations`); root.innerHTML = `<h1>Серия ${esc(state.episode.number)}</h1>${data.groups.map(group => `<section class="panel"><h2>${esc(group.label)}</h2>${group.items.map(item => `<button class="action secondary" data-translation="${item.id}">${esc(item.authorsSummary || item.title || 'Перевод')}</button>`).join('')}</section>`).join('')}<button class="action secondary back">Назад</button>`; useBack(); root.querySelector('.back').onclick = () => details(state.selected.item.series_id); root.querySelectorAll('[data-translation]').forEach(button => button.onclick = () => qualities(Number(button.dataset.translation))); } catch(error) { fail(error); } }
  async function qualities(translationId) { try { state.translation = translationId; const data = await api(`/api/translations/${translationId}/qualities`); root.innerHTML = `<h1>Качество</h1>${data.items.map(value => `<section class="panel"><strong>${value}p</strong><div><button class="action" data-watch="${value}">Смотреть</button><button class="action secondary" data-browser="${value}">Скачать</button><button class="action secondary" data-telegram="${value}">В Telegram</button></div></section>`).join('')}<button class="action secondary back">Назад</button>`; root.querySelector('.back').onclick = () => selectEpisode(state.episode.id); root.querySelectorAll('[data-watch]').forEach(button => button.onclick = () => player(Number(button.dataset.watch))); root.querySelectorAll('[data-browser]').forEach(button => button.onclick = () => queueDownload(Number(button.dataset.browser), 'browser')); root.querySelectorAll('[data-telegram]').forEach(button => button.onclick = () => queueDownload(Number(button.dataset.telegram), 'telegram')); } catch(error) { fail(error); } }
  async function queueDownload(quality, delivery) { try { const job = await api('/api/downloads', {method:'POST',body:JSON.stringify({series_id:state.selected.item.series_id,episode_id:state.episode.id,translation_id:state.translation,quality,delivery})}); root.innerHTML = `<h1>Подготовка поставлена в очередь</h1><p class="meta">Серия ${esc(state.episode.number)} · ${quality}p</p><p id="job-status">${esc(job.status)}</p><button class="action secondary back">К аниме</button>`; root.querySelector('.back').onclick = () => details(state.selected.item.series_id); const poll = async () => { const current = await api('/api/downloads/' + encodeURIComponent(job.id)); const node = root.querySelector('#job-status'); if (!node) return; node.textContent = current.status; if (current.status === 'ready') { const ticket = await api('/api/downloads/' + encodeURIComponent(job.id) + '/ticket', {method:'POST'}); node.innerHTML = `<a class="action" href="${ticket.url}">Скачать готовый MKV</a>`; return; } if (current.status === 'queued' || current.status === 'preparing') setTimeout(() => poll().catch(()=>{}), 2500); }; setTimeout(() => poll().catch(()=>{}), 1500); } catch(error) { fail(error); } }
  async function player(quality) { try { const result = await api('/api/play', {method:'POST', body:JSON.stringify({series_id:state.selected.item.series_id, episode_id:state.episode.id, translation_id:state.translation, quality})}); root.innerHTML = `<h1>${esc(state.selected.item.title)} · ${esc(state.episode.number)}</h1><video controls playsinline></video><p><button class="action secondary" id="fallback">Если видео не запустилось, использовать proxy</button></p><button class="action secondary back">Назад</button>`; const video = root.querySelector('video'); video.src = result.media_url; let last = 0; const save = (ended=false) => { if (!video.duration || Date.now()-last < 15000 && !ended) return; last=Date.now(); api('/api/progress',{method:'POST',body:JSON.stringify({series_id:state.selected.item.series_id,episode_id:state.episode.id,position_seconds:video.currentTime,duration_seconds:video.duration,ended})}).catch(()=>{}); }; video.addEventListener('timeupdate', () => save(false)); video.addEventListener('pause', () => save(false)); video.addEventListener('ended', () => save(true)); root.querySelector('#fallback').onclick = () => { video.src = result.proxy_url; video.play().catch(()=>{}); }; root.querySelector('.back').onclick = () => { save(false); details(state.selected.item.series_id); }; } catch(error) { fail(error); } }
  api('/api/me').then(async () => { const params = new URLSearchParams(location.search); const seriesId = Number(params.get('series_id')); if (seriesId) await details(seriesId); else await home(); }).catch(error => { root.innerHTML = `<p class="error">${esc(error.message)}${initData ? '' : '<br>Откройте страницу из Telegram.'}</p>`; });
})();
